apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  DB_HOST: {{ .Values.secrets.DB_HOST | b64enc | quote }}
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  OPENELIS_ATOMFEED_USER: {{ .Values.secrets.OPENELIS_ATOMFEED_USER | b64enc | quote }}
  OPENELIS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENELIS_ATOMFEED_PASSWORD | b64enc | quote }}
