global:
  storageClass: ""
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: openmrs
  tag: latest

service:
  type: ClusterIP
  port: 8080

config:
  DB_AUTO_UPDATE: true
  DB_CREATE_TABLES: true
  DB_NAME: openmrs
  DEBUG: false
  MODULE_WEB_ADMIN: false
  OPENELIS_HOST: openelis
  OPENELIS_PORT: '8052'

secrets:
  DB_HOST: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  OPENELIS_ATOMFEED_USER: ""
  OPENELIS_ATOMFEED_PASSWORD: ""

resources: {}

autoscaling:
  enabled: false

volumes:
  patientDocuments:
    capacity: "2Gi"
    claimName: openmrs-document-images-pvc
  initializerChecksums:
    capacity: "1Gi"
  clinicalForms:
    capacity: "1Gi"

nodeSelector: {}
affinity: {}
tolerations: {}
