apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: {{ .Values.metadata.labels.name }}
  name: {{ .Values.metadata.labels.name }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
