apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}
  name: {{ .Values.volumes.patient-documents.claimName }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.patient-documents.capacity }}
