apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}
  name: openmrs-initializer-checksums-pvc
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.initializerChecksums.capacity }}
