name: bahmni-india-package EMR deploy
on:
  push:
    branches: [main]
    paths:
      - "bahmni-emr/**"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: extract private key
        run: 'echo "$SSH_KEY" > ABDM-docker.pem'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ABDM_DOCKER_PEM}}
      - name: deploy Bahmni india package
        run: |
          sudo ssh -T -o "StrictHostKeyChecking no" -i "ABDM-docker.pem" ec2-user@ec2-15-206-93-89.ap-south-1.compute.amazonaws.com <<EOF
            cd bahmni
            docker stop openmrs
            docker pull bahmniindiadistro/bahmni-openmrs-abdm
            docker compose up -d openmrs
          EOF
  notification:
    name: notification
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy notification
        if: ${{ needs.deploy.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":":white_check_mark:  New bahmni openmrs docker Images deployed on https://abdm.bahmni-covid19.in/"}' ${{ secrets.SLACK_WEBHOOK_URL }}